version: '3.5'

services:
  mongodb:
    image: mongo:4.2.3
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      ticketdashboard:
        ipv4_address: 172.20.0.3
    
networks:
  ticketdashboard:
    name: ticketdashboard
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
